#!/usr/bin/env bash

set -e

prefix=~/src/llvm
build=Debug+Asserts

opt=$prefix/$build/bin/opt
clangxx=clang++

module=Hello
module_path=$prefix/$build/lib/LLVM$module.so

src=test

# Generate bytecode:
$clangxx -emit-llvm $src.cpp -S -o $src.ll

# Generate bitcode:
$clangxx -emit-llvm $src.cpp -c -o $src.bc

$opt -load $module_path -$(echo $module | tr '[:upper:]' '[:lower:]') \
    -time-passes -stats < $src.bc > /dev/null
