#!/usr/bin/env bash

set -e

prefix=~/src/llvm
build=Debug+Asserts

opt=$prefix/$build/bin/opt
clangxx=clang++
llvmdis=llvm-dis

module=Hello
module_path=$prefix/$build/lib/LLVM$module.so

src=test

CFLAGS="-O0"

# Generate bytecode:
$clangxx $CFLAGS -emit-llvm $src.cpp -S -o $src.ll

# Generate bitcode:
$clangxx $CFLAGS -emit-llvm $src.cpp -c -o $src.bc

# Generate exec:
$clangxx $CFLAGS $src.bc -o $src

# Run pass:
$opt -load $module_path -$(echo $module | tr '[:upper:]' '[:lower:]') \
     -stats < $src.bc > $src-pass.bc

# Generate bytecode:
$llvmdis $src-pass.bc

# Generate exec:
$clangxx $CFLAGS $src-pass.bc -o $src-pass

echo "Bytecode modifications:"
set +e
diff $src-pass.ll $src.ll
set -e

exit 0
